# Site settings
title: 徐萌
email: mengxu133@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  欢迎来到徐萌的博客！:D
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://meng.click" # the base hostname & protocol for your site
# twitter_username: 
# github_username:  jekyll

# Build settings
markdown: kramdown
